version: '3'

networks:
  app_network:

volumes:
  db_volume:
    external: false

services:

  ##
  ## HTTP
  ##
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: custom-nginx:latest
    container_name: nginx
    environment:
      - MASS_VHOST_ENABLE=1
      - MASS_VHOST_TLD=${VHOST_TDL}
      - MASS_VHOST_DOCROOT=${VHOST_ROOT}
      - MASS_VHOST_SSL_TYPE=both
      - MASS_VHOST_SSL_GEN=1
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=php
      - PHP_FPM_SERVER_PORT=9000
    networks:
      - app_network
    ports:
      - "${LOCAL_PORT_HTTP:-80}:80"
      - "${LOCAL_PORT_HTTPS:-443}:443"
    depends_on:
      - php
    volumes:
      - ./app:/shared/httpd
      - ./docker/nginx/volumes/ca:/ca
      - ./docker/nginx/volumes/log:/var/log/nginx-stable

  ##
  ## PHP
  ##
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: custom-php:latest
    container_name: php
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    networks:
      - app_network
    depends_on:
      - db
    volumes:
      - ./app:/shared/httpd
      - ./docker/php/volumes/conf/php.ini:/usr/local/etc/php/conf.d/docker-php.ini
    restart: always

  ##
  ## DATABASE
  ##
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    networks:
      - app_network
    ports:
      - "${LOCAL_PORT_DB:-3306}:3306"
    volumes:
      - db_volume:/var/lib/mysql/
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  ##
  ## CACHE
  ##
  cache:
    image: memcached:latest
    container_name: cache
    networks:
      - app_network
    ports:
      - "${LOCAL_PORT_CACHE:-11211}:11211"
    depends_on:
      - php
      - db
    restart: always
